"use client";

import { ChapterLengthPlanList } from "@/components/ChapterLengthPlanList";
import { StructureChapterReview } from "@/components/StructureChapterReview";
import { Button } from "@/components/ui/button";
import {
  computeTotalPlannedLength,
  formatLengthLabel,
} from "@/lib/length-planning";
import { CHAPTER_OUTLINE_FALLBACK_MESSAGE } from "@/lib/chapter-architect-context";
import type { Chapter, PartPlan, StoryProject } from "@/lib/types";
import { Check, ChevronDown, ChevronUp, RefreshCw } from "lucide-react";
import { useState } from "react";

interface StructureDesignerProps {
  project: StoryProject;
  isRunning?: boolean;
  onApproveAndContinue: () => void;
  onRegenerateStructure: () => void;
  onUpdateStructure: (parts: PartPlan[]) => void;
  onBackToWorkspace?: () => void;
}

export function StructureDesigner({
  project,
  isRunning = false,
  onApproveAndContinue,
  onRegenerateStructure,
  onUpdateStructure,
  onBackToWorkspace,
}: StructureDesignerProps) {
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const localParts = project.storyBible.parts?.length
    ? project.storyBible.parts
    : project.structure.parts ?? [];

  const unit = project.structure.lengthUnit;
  const totalPlanned = computeTotalPlannedLength(localParts);
  const chapterCount = localParts.flatMap((p) => p.chapters).length;
  const customPerChapter =
    project.structure.customPerChapterLengthEnabled ?? false;

  const handlePartsChange = (parts: PartPlan[]) => {
    onUpdateStructure(parts);
  };

  const updateChapter = (
    pi: number,
    ci: number,
    patch: Partial<Chapter>
  ) => {
    const next = localParts.map((p, i) =>
      i === pi
        ? {
            ...p,
            chapters: p.chapters.map((c, j) =>
              j === ci ? { ...c, ...patch } : c
            ),
          }
        : p
    );
    handlePartsChange(next);
  };

  const updatePart = (pi: number, patch: Partial<PartPlan>) => {
    const next = localParts.map((p, i) => (i === pi ? { ...p, ...patch } : p));
    handlePartsChange(next);
  };

  return (
    <div className="surface-card premium-border rounded-2xl p-6 space-y-5">
      <div>
        <h2 className="text-xl font-semibold text-[#F8FAFC]">
          Structure Designer
        </h2>
        <p className="text-sm text-[#94A3B8] mt-1">
          Titles and purposes were generated by the Chapter Architect. Edit only
          if needed. Long works draft one chapter at a time.
        </p>
        {project.structureFallbackUsed && (
          <p className="text-sm text-amber-300/90 mt-2">
            {CHAPTER_OUTLINE_FALLBACK_MESSAGE}
          </p>
        )}
      </div>

      <div className="text-xs text-[#94A3B8] flex flex-wrap gap-4">
        <span>
          Total planned length:{" "}
          <span className="text-[#F8FAFC] font-medium">
            about {formatLengthLabel(totalPlanned, unit, project.language)}
          </span>
        </span>
        <span>
          {chapterCount} chapters · {localParts.length} parts
        </span>
      </div>

      <StructureChapterReview parts={localParts} language={project.language} />

      <div className="border-t border-white/10 pt-3">
        <button
          type="button"
          className="flex items-center gap-2 text-sm font-medium text-[#CBD5E1] hover:text-[#F8FAFC]"
          onClick={() => setAdvancedOpen(!advancedOpen)}
          disabled={isRunning}
        >
          {advancedOpen ?
            <ChevronUp className="size-4" />
          : <ChevronDown className="size-4" />}
          Edit structure details
        </button>

        {advancedOpen && (
          <div className="mt-4 space-y-4">
            {customPerChapter && localParts.length > 0 && (
              <ChapterLengthPlanList
                parts={localParts}
                language={project.language}
                disabled={isRunning}
                advancedMode
                showAdvancedDistribute
                onPartsChange={handlePartsChange}
              />
            )}

            <div className="space-y-4 max-h-[400px] overflow-y-auto pr-1">
              {localParts.map((part, pi) => (
                <div
                  key={part.id}
                  className="rounded-xl border border-white/10 bg-[#172033]/60 p-4 space-y-3"
                >
                  <div className="grid gap-2 sm:grid-cols-2">
                    <div>
                      <label className="text-xs text-[#94A3B8]">Part title</label>
                      <input
                        value={part.title}
                        onChange={(e) =>
                          updatePart(pi, { title: e.target.value })
                        }
                        disabled={isRunning}
                        className="mt-1 flex h-9 w-full rounded-md border border-white/12 bg-[#0B1020] px-3 text-sm text-[#F8FAFC]"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-[#94A3B8]">Part purpose</label>
                      <input
                        value={part.purpose}
                        onChange={(e) =>
                          updatePart(pi, { purpose: e.target.value })
                        }
                        disabled={isRunning}
                        className="mt-1 flex h-9 w-full rounded-md border border-white/12 bg-[#0B1020] px-3 text-sm text-[#F8FAFC]"
                      />
                    </div>
                  </div>

                  {part.chapters.map((ch, ci) => (
                    <div
                      key={ch.id ?? ch.number}
                      className="rounded-lg border border-white/8 bg-[#0B1020]/80 p-3 space-y-2"
                    >
                      <p className="text-xs font-medium text-[#F5C542]">
                        Chapter {ch.number}
                      </p>
                      <div className="grid gap-2 sm:grid-cols-2">
                        <div>
                          <label className="text-xs text-[#94A3B8]">Title</label>
                          <input
                            value={ch.title}
                            onChange={(e) =>
                              updateChapter(pi, ci, { title: e.target.value })
                            }
                            disabled={isRunning}
                            className="mt-1 flex h-8 w-full rounded-md border border-white/12 bg-[#172033] px-2 text-sm"
                          />
                        </div>
                        <div>
                          <label className="text-xs text-[#94A3B8]">Purpose</label>
                          <input
                            value={ch.purpose}
                            onChange={(e) =>
                              updateChapter(pi, ci, { purpose: e.target.value })
                            }
                            disabled={isRunning}
                            className="mt-1 flex h-8 w-full rounded-md border border-white/12 bg-[#172033] px-2 text-sm"
                          />
                        </div>
                      </div>
                      <div>
                        <label className="text-xs text-[#94A3B8]">
                          Emotional turn
                        </label>
                        <input
                          value={ch.emotionalTurn}
                          onChange={(e) =>
                            updateChapter(pi, ci, {
                              emotionalTurn: e.target.value,
                            })
                          }
                          disabled={isRunning}
                          className="mt-1 flex h-8 w-full rounded-md border border-white/12 bg-[#172033] px-2 text-sm"
                        />
                      </div>
                      <div>
                        <label className="text-xs text-[#94A3B8]">
                          Key events (comma-separated)
                        </label>
                        <input
                          value={ch.keyEvents?.join(", ") ?? ""}
                          onChange={(e) =>
                            updateChapter(pi, ci, {
                              keyEvents: e.target.value
                                .split(",")
                                .map((s) => s.trim())
                                .filter(Boolean),
                            })
                          }
                          disabled={isRunning}
                          className="mt-1 flex h-8 w-full rounded-md border border-white/12 bg-[#172033] px-2 text-sm"
                        />
                      </div>
                      {!customPerChapter && (
                        <div>
                          <label className="text-xs text-[#94A3B8]">
                            Approximate length
                          </label>
                          <div className="mt-1 flex items-center gap-2">
                            <input
                              type="number"
                              min={100}
                              value={ch.lengthPlan?.targetLength ?? ""}
                              onChange={(e) => {
                                const targetLength =
                                  Number(e.target.value) || 0;
                                updateChapter(pi, ci, {
                                  lengthPlan: {
                                    targetLength,
                                    unit,
                                    minLength: Math.floor(targetLength * 0.85),
                                    maxLength: Math.ceil(targetLength * 1.15),
                                  },
                                });
                              }}
                              disabled={isRunning}
                              className="w-28 h-8 rounded-md border border-white/12 bg-[#172033] px-2 text-sm"
                            />
                            <span className="text-xs text-[#94A3B8]">{unit}</span>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      <div className="flex flex-wrap gap-2 pt-2 border-t border-white/10">
        <Button
          variant="premium"
          onClick={onApproveAndContinue}
          disabled={isRunning || chapterCount === 0}
        >
          <Check className="mr-2 size-4" />
          Continue with Structure
        </Button>
        <Button
          variant="glass"
          onClick={onRegenerateStructure}
          disabled={isRunning}
        >
          <RefreshCw className="mr-2 size-4" />
          Regenerate Structure
        </Button>
        {onBackToWorkspace && (
          <Button variant="ghost" onClick={onBackToWorkspace} disabled={isRunning}>
            Back to Workspace
          </Button>
        )}
      </div>
    </div>
  );
}
